- name: "Check if the logging-fluentd DaemonSet is deployed"
  shell:  "oc get ds logging-fluentd -n {{ logging_project }}"
  register: fluentd_ds_deployed
  failed_when: false

- set_fact:
    infra_not_deployed: true
  when: '"Error" in ''{{ fluentd_ds_deployed.stderr }}'''
