---
- name: "Got to logging project"
  shell: oc project {{ logging_project }}

- name: delete k8s resources
  shell: "oc delete {{ item }} || true"
  with_items:
  - ds logging-fluentd
  - templates fluentd-roles-template
  - sa aggregated-logging-fluentd
  - clusterrole daemonset-admin
  - rolebinding aggregated-fluentd-binding
  - templates fluentd-daemonset-template

- name: "Delete tmp files from remote"
  file: path=/tmp/{{ item }} state=absent
  with_items:
  - fluentd-daemonset.yaml
  - roles-setup.yaml

- name: delete configmaps
  shell: "oc delete configmap fluent-{{ item }}-cm|| true"
  with_items: '{{ config_list.stdout_lines }}'

- name: "Delete config files from remote"
  file: path=/tmp/{{ item }} state=absent
  with_items: '{{ config_list.stdout_lines }}'

- name: unlabel
  shell:  "oc label node --overwrite=true --all logging-infra-"
