- name: "Go to logging project"
  command: oc project {{ logging_project }}

- name: delete old configmaps
  shell: "oc delete configmap fluent-{{ item }}-cm|| true"
  with_items: '{{ config_list.stdout_lines }}'

- name: "Copy fluent configs to the remote"
  copy: 'src="{{ config_path }}/{{ item }}" dest=/tmp/'
  with_items: '{{ config_list.stdout_lines }}'

- name: "Create fluend config configMaps"
  command: "oc create configmap fluent-{{ item }}-cm --from-file=/tmp/{{ item }}"
  with_items: '{{ config_list.stdout_lines }}'

- name: "Remove labeling from the nodes"
  shell:  "oc label node --overwrite=true --all logging-infra-"

- name: "Forcefully kill all the pods"
  shell: "oc delete pod -l component=fluentd --grace-period=0"

- name: "Deploy fluentd by labeling the node"
  shell:  "oc label node --overwrite=true --all logging-infra=fluentd"
